- name: Ensure Node.js is installed
  hosts: localhost
  become: yes
  tasks:
    - name: Add Node.js PPA
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main'
        state: present
        filename: 'nodesource'
        update_cache: yes
    
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
