- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present

- name: Change Nginx port to 81
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: 'listen 80 default_server;'
    line: 'listen 81 default_server;'
  notify:
    - restart nginx

handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
